// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using Microsoft.EntityFrameworkCore.Migrations;

namespace JetBrains.Plugins.Models.Migrations
{
    public partial class AnnotateRequirements : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PluginDependency_Plugins_DependencyID",
                table: "PluginDependency");

            migrationBuilder.DropForeignKey(
                name: "FK_PluginDependency_Plugins_DependerID",
                table: "PluginDependency");

            migrationBuilder.AlterColumn<decimal>(
                name: "DependerID",
                table: "PluginDependency",
                nullable: false,
                oldClrType: typeof(decimal),
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "DependencyID",
                table: "PluginDependency",
                nullable: false,
                oldClrType: typeof(decimal),
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_PluginDependency_Plugins_DependencyID",
                table: "PluginDependency",
                column: "DependencyID",
                principalTable: "Plugins",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_PluginDependency_Plugins_DependerID",
                table: "PluginDependency",
                column: "DependerID",
                principalTable: "Plugins",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PluginDependency_Plugins_DependencyID",
                table: "PluginDependency");

            migrationBuilder.DropForeignKey(
                name: "FK_PluginDependency_Plugins_DependerID",
                table: "PluginDependency");

            migrationBuilder.AlterColumn<decimal>(
                name: "DependerID",
                table: "PluginDependency",
                nullable: true,
                oldClrType: typeof(decimal));

            migrationBuilder.AlterColumn<decimal>(
                name: "DependencyID",
                table: "PluginDependency",
                nullable: true,
                oldClrType: typeof(decimal));

            migrationBuilder.AddForeignKey(
                name: "FK_PluginDependency_Plugins_DependencyID",
                table: "PluginDependency",
                column: "DependencyID",
                principalTable: "Plugins",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PluginDependency_Plugins_DependerID",
                table: "PluginDependency",
                column: "DependerID",
                principalTable: "Plugins",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
