// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using Microsoft.EntityFrameworkCore.Migrations;

namespace JetBrains.Plugins.Models.Migrations
{
    public partial class MakeDependerRelease : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PluginDependency_Plugins_DependerID",
                table: "PluginDependency");

            migrationBuilder.DropForeignKey(
                name: "FK_PluginDependency_PluginRelease_PluginReleaseID",
                table: "PluginDependency");

            migrationBuilder.DropIndex(
                name: "IX_PluginDependency_PluginReleaseID",
                table: "PluginDependency");

            migrationBuilder.DropColumn(
                name: "PluginReleaseID",
                table: "PluginDependency");

            migrationBuilder.AddForeignKey(
                name: "FK_PluginDependency_PluginRelease_DependerID",
                table: "PluginDependency",
                column: "DependerID",
                principalTable: "PluginRelease",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PluginDependency_PluginRelease_DependerID",
                table: "PluginDependency");

            migrationBuilder.AddColumn<decimal>(
                name: "PluginReleaseID",
                table: "PluginDependency",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_PluginDependency_PluginReleaseID",
                table: "PluginDependency",
                column: "PluginReleaseID");

            migrationBuilder.AddForeignKey(
                name: "FK_PluginDependency_Plugins_DependerID",
                table: "PluginDependency",
                column: "DependerID",
                principalTable: "Plugins",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_PluginDependency_PluginRelease_PluginReleaseID",
                table: "PluginDependency",
                column: "PluginReleaseID",
                principalTable: "PluginRelease",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
