// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JetBrains.Plugins.Models.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Categories",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    Name = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Categories", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "Plugins",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    Name = table.Column<string>(nullable: false),
                    CategoryID = table.Column<long>(nullable: false),
                    PluginID = table.Column<string>(nullable: false),
                    Description = table.Column<string>(nullable: false),
                    Vendor_Name = table.Column<string>(nullable: true),
                    Vendor_URL = table.Column<string>(nullable: true),
                    Vendor_Email = table.Column<string>(nullable: true),
                    Tags = table.Column<List<string>>(nullable: false),
                    Rating = table.Column<double>(nullable: false),
                    ProjectURL = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Plugins", x => x.ID);
                    table.ForeignKey(
                        name: "FK_Plugins_Categories_CategoryID",
                        column: x => x.CategoryID,
                        principalTable: "Categories",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "PluginRelease",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    PluginID = table.Column<long>(nullable: false),
                    ChangeNotes = table.Column<string>(nullable: false),
                    Downloads = table.Column<long>(nullable: false),
                    Size = table.Column<long>(nullable: false),
                    UploadedAt = table.Column<DateTime>(nullable: false),
                    Hash = table.Column<string>(nullable: false),
                    Version = table.Column<string>(nullable: false),
                    CompatibleWith_SinceBuild_ProductID = table.Column<string>(nullable: true),
                    CompatibleWith_SinceBuild_Branch = table.Column<int>(nullable: false),
                    CompatibleWith_SinceBuild_Build = table.Column<int>(nullable: true),
                    CompatibleWith_SinceBuild_Extra = table.Column<List<int>>(nullable: true),
                    CompatibleWith_UntilBuild_ProductID = table.Column<string>(nullable: true),
                    CompatibleWith_UntilBuild_Branch = table.Column<int>(nullable: false),
                    CompatibleWith_UntilBuild_Build = table.Column<int>(nullable: true),
                    CompatibleWith_UntilBuild_Extra = table.Column<List<int>>(nullable: true),
                    Dependencies = table.Column<List<string>>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PluginRelease", x => x.ID);
                    table.ForeignKey(
                        name: "FK_PluginRelease_Plugins_PluginID",
                        column: x => x.PluginID,
                        principalTable: "Plugins",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PluginRelease_PluginID",
                table: "PluginRelease",
                column: "PluginID");

            migrationBuilder.CreateIndex(
                name: "IX_Plugins_CategoryID",
                table: "Plugins",
                column: "CategoryID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PluginRelease");

            migrationBuilder.DropTable(
                name: "Plugins");

            migrationBuilder.DropTable(
                name: "Categories");
        }
    }
}
